### ISSUE TITLE
Invariant Violation: Native component for "RNSpruceView" does not exist

### ISSUE THREAD

**Issue by joaoalbertocsjunior** [prscX/react-native-spruce#2]
**What i did:**

react-native init myproject

cd myproject

yarn add react-native-spruce

react-native link

copy-paste how to use section on readme.

**What i got:**

Invariant Violation: Native component for "RNSpruceView" does not exist

[https://ibb.co/kJ2zEG](https://ibb.co/kJ2zEG)

**Comment by prscX** [comment]
Thanks @joaoalbertocsjunior for reporting the issue.

Looking like the library is not linked to your app. Can you please verify whether the library is adding into your android app: `settings.grade, build.gradle and MainApplication`.

You can run below command to again link the library

`react-native link react-native-spruce`

Please let me know in case it does not work.

Thanks
Pranav

**Comment by joaoalbertocsjunior** [comment]
I'd like to thank you for these awesome modules and for the fast reply!

I've checked, and it appears that automatic linking does not link it to build.gradle

How should i manually link it?

**Comment by prscX** [comment]
Thanks @joaoalbertocsjunior for the appreciation 😊 

For manually linking, there 3 files we need to change in order to link any library:
- `settings.gradle`: It contains relative path to the library
- `build.gradle`: Here we have to add library in repositories section for compiling the library
- `MainApplication`: Here we have to add library module package in modules list

Hope this will provide some context on how to achieve manually linking any library

Thanks
Pranav
