### ISSUE TITLE
Unable to resolve module 'unimplementedView'

### ISSUE THREAD

**Issue by mustafaskir** [prscX/react-native-spruce#7]
i tried SpruceExample in your pacakege
[SpruceExample](https://github.com/prscX/react-native-spruce/tree/master/SpruceExample)
![spruc](https://user-images.githubusercontent.com/15132084/38768915-4421a234-4003-11e8-9453-9d947a363d01.png)

**Comment by prscX** [comment]
Thanks @mustafaskir for reporting the issue.

Currently `react-native-spruce` is not supported for iOS platform due unavailability of native objective-c wrappers. Please refer [ISSUE: 101](https://github.com/willowtreeapps/spruce-ios/issues/101) for the details.

However I have added separate `index.ios.js` & `index.android.js` files in order to resolve the `UnimplementedView` error. Please install latest `v0.0.5` for the same.

Please let me know in case you still face the same issue.

Thanks
</ Pranav >
